/**
 * Split docx-preview's pages that run longer than their paper.
 *
 * docx-preview breaks pages only where the file says to: explicit page
 * breaks, and the positions Word wrote the last time it laid the document out
 * (`lastRenderedPageBreak`). A document Word never saved — generated by a tool,
 * or written by another editor — has neither, and came out as one endlessly
 * long page: one entry in the page list, "1 / 1" in the counter, and a PDF
 * whose continuation pages had no margins.
 *
 * This measures each page in the live DOM and moves whatever overflows the
 * paper onto a new page of the same size, with the same header and footer —
 * block by block, and row by row through a table. It is our own wrapper
 * around docx-preview's output; the library is not patched.
 */

/** A page's children, as docx-preview lays them out (flex column). */
function partsOf(section: HTMLElement) {
  const children = Array.from(section.children) as HTMLElement[]
  const article = children.find(c => c.tagName === 'ARTICLE') ?? null
  return {
    article,
    header: children.find(c => c.tagName === 'HEADER') ?? null,
    footer: children.find(c => c.tagName === 'FOOTER') ?? null,
  }
}

/** An empty page shaped like `section`: same paper, header and footer. */
function emptyPageLike(section: HTMLElement, article: HTMLElement): { page: HTMLElement; body: HTMLElement } {
  const page = section.cloneNode(false) as HTMLElement
  const { header, footer } = partsOf(section)
  const body = article.cloneNode(false) as HTMLElement
  if (header) page.appendChild(header.cloneNode(true))
  page.appendChild(body)
  if (footer) page.appendChild(footer.cloneNode(true))
  return { page, body }
}

/**
 * Move the rows of `table` that end below `limit` (a viewport y) into a copy
 * of the table, returned; null when no row fits or none overflows.
 */
function splitTable(table: HTMLTableElement, limit: number): HTMLTableElement | null {
  const rows = Array.from(table.rows)
  const first = rows.findIndex(r => r.getBoundingClientRect().bottom > limit)
  if (first <= 0) return null
  const rest = table.cloneNode(false) as HTMLTableElement
  for (const child of Array.from(table.children)) {
    if (child.tagName === 'COLGROUP') rest.appendChild(child.cloneNode(true))
  }
  const body = document.createElement('tbody')
  rest.appendChild(body)
  for (const row of rows.slice(first)) body.appendChild(row)
  return rest
}

/**
 * Split every page of `wrapper` that overflows its paper. Returns the pages,
 * in order. Safe to run again: pages that fit are left alone.
 */
export function paginateDocx(wrapper: HTMLElement): HTMLElement[] {
  const pages = (): HTMLElement[] =>
    Array.from(wrapper.children).filter(c => c.tagName === 'SECTION') as HTMLElement[]

  // A page can overflow by more than one page, so its remainder is checked in
  // turn; the guard bounds a pathological document.
  for (let i = 0, guard = 0; i < pages().length && guard < 5000; i++, guard++) {
    const section = pages()[i]
    const { article, footer } = partsOf(section)
    if (!article) continue
    const style = getComputedStyle(section)
    const paper = parseFloat(style.minHeight)
    if (!paper) continue
    const rect = section.getBoundingClientRect()
    const width = parseFloat(style.width)
    // The page is drawn under a CSS zoom; measure in screen pixels and scale
    // the paper's own size to match.
    const scale = width > 0 ? rect.width / width : 1
    if (rect.height <= paper * scale + 1) continue

    const padBottom = parseFloat(style.paddingBottom) * scale
    const footerHeight = footer ? footer.getBoundingClientRect().height : 0
    const limit = rect.top + paper * scale - padBottom - footerHeight

    const blocks = Array.from(article.children) as HTMLElement[]
    let cut = blocks.findIndex(b => b.getBoundingClientRect().bottom > limit)
    if (cut < 0) continue
    let carried: HTMLElement | null = null
    if (blocks[cut].tagName === 'TABLE') {
      // A table that starts on this page continues on the next one.
      carried = splitTable(blocks[cut] as HTMLTableElement, limit)
      if (carried) cut += 1
    }
    // A single block taller than a page stays where it is: there is nothing
    // to split it at, and moving it would only leave an empty page behind.
    if (cut === 0 && !carried) continue

    const { page, body } = emptyPageLike(section, article)
    if (carried) body.appendChild(carried)
    for (const block of blocks.slice(cut)) body.appendChild(block)
    if (!body.firstChild) continue
    section.after(page)
  }
  return pages()
}
